//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MyBlogLister.Data;

namespace MyBlogLister.BusinessLayer.BusinessLayer
{
    /// <summary>
    ///     Provides access to data from the Posts table in the data
    ///     source.
    /// </summary>
    public partial class PostRepository : BloggingRepository<Post>,
        IPostRepository
    {
        /// <summary>
        ///     Constructs a new instance of
        ///     <see cref="T:MyBlogLister.BusinessLayer.BusinessLayer.PostRepository" /> and
        ///     returns a reference to it.
        /// </summary>
        public PostRepository(BloggingContext context) : base(context)
        {
            // TODO: Add code here to initialize the Posts repository.
        }
        
        // TODO: Add another part of this (partial) class to implement custom functionality.
        
    }
}
